[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "digitz_erp"
version = "1.0.0"  # <--- Recommended
description = "DIGITZ ERP"
authors = [
    { name="Rupesh P", email="rupesh@techxceltech.com" }
]
dependencies = []
